print('Enter your first number')
num1= input()
print("Ok it changes now")
print('Enter your second number')
print('my name is speed ')
num2= input()
print("Total number is ",int(num1)+int(num2))
